server:
    port: 8081

mybatis:
    #?? mapper.xml ??????
    mapper-locations: classpath:mapper/*.xml
    # ????? mapper.xml ?????????
    #type-aliases-package: com.cl.springboot.pojo
    #configuration:
    #??????
    #map-underscore-to-camel-case: true
    # sql?????
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:orcl
        data-username: system
        password: 1234567

